### ISSUE TITLE
plan run-order command ambiguous output

### ISSUE THREAD

**Issue by ShimonOhayon** [mineiros-io/terramate#296]
Hi, This is my First Issue for `mineiros` i didn't see any contribution guide line so i  will do my best to supply all information needed.

When running `terramate plan run-order` the output are only modules [names](https://github.com/mineiros-io/terramate/blob/main/cmd/terramate/cli/cli.go#L689) making it hard to know which module  actually is going to be execute when re using the same module names in the stack, Just like in the [terramate-example-code-generation](https://github.com/mineiros-io/terramate-example-code-generation) repository.

Here are the  example outputs:

```
terramate stacks list

stacks/prod/cloud-runs/app1
stacks/prod/cloud-runs/app2
stacks/staging/cloud-runs/app1
stacks/staging/cloud-runs/app2
```
```
terramate plan run-order

app1
app2
app1
app2
```
 
I would expect to have the relative path in the  run order output - or as a _metdata_ along side the model name. So i would know if `prod` is before `staging`.

terramate version = `0.0.11`

**Comment by mariux** [comment]
Hi @ShimonOhayon

thanks for reporting this issue. We will release 0.0.12 as soon as possible where we also restructured our command line arguments for the upcoming 0.1 release and marked some as experimental, e.g the run-order. 

Your suggestion makes perfect sense to me :) the team (@i4ki and @katcipis) will check the details and come back to you asap and ofc release 0.0.12.

We will also set up issue templates and contribution guidelines in the process of releasing 0.1. Please also expect some content around terramate ;)

in the meanwhile latest `main` of terramate can be used to also run the latest `main` of the examples repository. We also adjusted the stack names in there so not every stack is named equally.

**Comment by ShimonOhayon** [comment]
Cool ! , Looking forward for the upcoming releases.

**Comment by katcipis** [comment]
Hi @ShimonOhayon,

Thanks for reaching out about this.

Right now the run-order is listing the stacks names, which indeed can lead to ambiguous outputs since there are no constraints on how stacks are named. The `run-order` sub-command was moved inside "experimental" because we are still figuring out a stable output for it. I'm prone to having the output to be the same as what we have on `terramate list`.

WDYT @i4ki ?

**Comment by i4ki** [comment]
yeah it makes sense!

**Comment by i4ki** [comment]
@ShimonOhayon you can safely run `terramate run --dry-run -- any command here` to plan what's going to be executed, it outputs the `run order` using the stack.name and stack.path.
Maybe it's still not the ideal output but hopefully, this helps you before we fix this.

**Comment by ShimonOhayon** [comment]
@i4ki @katcipis  - Thank you!
Can be closed from my side.
