### ISSUE TITLE
[FEATURE] Homebrew installation option for MacOS and Linux

### ISSUE THREAD

**Issue by yermulnik** [mineiros-io/terramate#360]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Provide an option to install `Terramate` via Homebrew Tap (https://docs.brew.sh/Taps) or Homebrew Core (https://github.com/Homebrew/homebrew-core), including compatibility with Linux (https://docs.brew.sh/Homebrew-on-Linux).

**Describe alternatives you've considered**
Native installation with Golang lacks plenty of features supported by Homebrew and/or package managers.

**Additional context**
Would be good to have such an option. Thank you.

**Comment by soerenmartius** [comment]
Hey @yermulnik! Thanks for requesting this! Indeed we should make Terramate installable via Homebrew. Let me sync with the team to see when we can put this on the roadmap and come back to you!

**Comment by chenrui333** [comment]
I have just filed [a homebrew-core PR](https://github.com/Homebrew/homebrew-core/pull/102260) to include this tool.

**Comment by yermulnik** [comment]
Yay 🎉 Thank you for the quickest turnaround ever! 🚀

**Comment by soerenmartius** [comment]
Amazing! Thank you - will update the README tomorrow!

**Comment by soerenmartius** [comment]
Added instructions in https://github.com/mineiros-io/terramate/pull/361/files

Again, thanks for requesting this @yermulnik and @chenrui333 for providing the formula!
