### ISSUE TITLE
[QUESTION] Is it possible to dynamically generate stacks based on used/all regions?

### ISSUE THREAD

**Issue by it-praktyk** [mineiros-io/terramate#363]
Hi,
thank you for sharing the Terramate project.

I'm curious, is it possible to use Terramate to dynamically generate stacks based on regions data gathered from AWS by using  [aws_region data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region).

My case is to instantiate some resources for all/used regions.

**Comment by it-praktyk** [comment]
I've found [the Terraform issue](https://github.com/hashicorp/terraform/issues/25244).

**Comment by mariux** [comment]
Hi @it-praktyk ..

Sorry for the late reply as we were busy adding new features and fixing some minor bugs ;)

Terramate is not using any provider features of Terraform so it can not execute data sources. 

What is your use case that you think of and what you want to use the result of the data source for?

You could use Globals to to create a list of regions and generate code referencing them or you can use the new conditional feature to create code for various situations. 

Please see https://github.com/mineiros-io/terramate/issues/368 and https://github.com/mineiros-io/terramate/pull/367 if this is something that would support you.

Please state the exact use-case so we can either point you to a solution or add it to our roadmap. Provider config is one of the central problems we want to solve.

Best, marius & the team ;)
