### ISSUE TITLE
[QUESTION] Is conditional generation possible?

### ISSUE THREAD

**Issue by sergeyshevch** [mineiros-io/terramate#368]
Can I conditional generate hcl depending on some global variable?

Use case: I need to add `assume_role` role to  `aws` provider only if role name exists in globals

Code example:

```
globals {
  region = "us-east-1"
  aws_role_arn = ""
}

generate_hcl "backend.tf" {
  content {
    provider "aws" {
      region = "${global.region}"
      dynamic "assume_role" {
        for_each = global.aws_role_arn != "" ? [true] : []

        content {
          role_arn = global.aws_role_arn
        }
      }
    }
  }
}
```

Current code will correctly handle such case but it will provide ugly generated code. 

Generated code:
```
provider "aws" {
  region = "us-east-1"
  dynamic "assume_role" {
    for_each = "" != "" ? [true] : []
    content {
      role_arn = ""
    }
  }
}
```

**Comment by katcipis** [comment]
[v0.1.4](https://github.com/mineiros-io/terramate/releases/tag/v0.1.4) added conditional code generation. Let me know if it solved your problem @sergeyshevch :-)

**Comment by sergeyshevch** [comment]
@katcipis Totaly solved! Thank you!
