### ISSUE TITLE
[BUG] Codegeneration provides inccorrect code

### ISSUE THREAD

**Issue by sergeyshevch** [mineiros-io/terramate#376]
**Describe the bug**

I have next string in my generate_hcl function call
`terraform${tm_try(global.state_bucket_key, terramate.path)}/terraform.tfstate`

When I generate stack in path `/live/production/us-east-1/infrastructure/route53-association`

if provide strange value

Correct value `terraform/live/production/us-east-1/infrastructure/route53-association/terraform.tfstate`
Current value `terraform/live/production/us-east-1/infrastructure/route53-associationciationorm.tfstate`

`state_bucket_key` variable is undefined

**Environment (please complete the following information):**
 - OS: [e.g. Linux] MacOS (MBP M1)
 - OS Version [e.g. Ubuntu 20.04] 
 - Git Version [e.g. 2.35.1] (git --version)
 - Terramate Version [e.g. 0.1.0] (terramate --version) 0.1.3

**Additional context**

**Comment by i4ki** [comment]
Hi @sergeyshevch 

Thank you for reporting this. I was able to reproduce the issue and will provide a patch ASAP.

**Comment by mariux** [comment]
@sergeyshevch we just merged a patch today that will be included in the next release of terramate. Please feel free to try current `main` branch or wait for the next release which will be available withing the next 24h ;)

**Comment by katcipis** [comment]
The new v0.1.5 release should address this issue: https://github.com/mineiros-io/terramate/releases/tag/v0.1.5
