### ISSUE TITLE
[BUG] Label conflict in conditional code generation when different conditions is used

### ISSUE THREAD

**Issue by sergeyshevch** [mineiros-io/terramate#390]
**Describe the bug**
When we conditionally generate code we should allow same names when only one condition is valid

**To Reproduce**

Try to run terraform generate with next code snippet

```

generate_hcl "providers.gen.tf" {
  condition = global.aws_role_arn != ""

  content {
    provider "aws" {
      region = "${global.region}"
      assume_role {
        role_arn = global.aws_role_arn
      }
    }
  }
}

generate_hcl "providers.gen.tf" {
  condition = global.aws_role_arn == ""

  content {
    provider "aws" {
      region = "${global.region}"
    }
  }
}
```

**Expected behavior**
Code should be generated without errors because only one condition will be valid at the same time

**Log Output**
Add logs from Terramate to help debug your problem.

```
- stack /some-private-stack
        error: label conflict detected: loading generate_hcl: /global.tm.hcl has blocks with same label "providers.gen.tf"

Hint: '+', '~' and '-' means the file was created, changed and deleted, respectively.
```

**Environment (please complete the following information):**
 - OS: [e.g. Linux] MacOS (MBP M1)
 - OS Version [e.g. Ubuntu 20.04]
 - Git Version [e.g. 2.35.1] (git --version) git version 2.32.0 (Apple Git-132)
 - Terramate Version [e.g. 0.1.0] (terramate --version) 0.1.4

**Additional context**

**Comment by katcipis** [comment]
Thanks for the reporting this in detail :100: , will work on it ASAP.

**Comment by sergeyshevch** [comment]
Another interesting idea. If we generate two blocks with the same filename we can just join them. And add into generated code comments about it. It will also help. So now I have a lot of generated files (2-5 for stack) and than I can have one generated file with all code

**Comment by katcipis** [comment]
The fix is released on [v0.1.6](https://github.com/mineiros-io/terramate/releases/tag/v0.1.6)

**Comment by sergeyshevch** [comment]
@i4ki @katcipis  Are you have plans to add ability to use multiple generate_hcl block for one generated file?

For example, I have 3 generate_hcl blocks with the same file name (and maybe with some flag-like `merge`) and its content will be generated in one file. 

It's useful because I still have multiples generated files (up to 5) in single stack to share some variables between stacks

Example:

```
generate_hcl "names.gen.tf" {
  content {
    locals {
      eks_name = global.common_name
      vpc_name = global.common_name
    }
  }
}

generate_hcl "names.gen.tf" {
  condition = tm_try(global.generate_athena_values, false)

  content {
    locals {
      athena_results_bucket = global.athena_results_bucket
    }
  }
}
```

Result

main.gen.tf:
```
locals {
  eks_name = "name"
  vpc_name = "name"
}
locals {
  athena_results_bucket = "name"
}
```

**Comment by katcipis** [comment]
Hi @sergeyshevch,

We have an internal roadmap that we are working on, we are going to discuss the idea soon and then we can give you some feedback.

Thanks for the suggestion :100:

**Comment by sergeyshevch** [comment]
@katcipis Any new info here? Maybe we can reopen this issue or move questions to another?

**Comment by katcipis** [comment]
Hi @sergeyshevch,

I think a new feature issue would make more sense than re-opening this one, if you mean the new feature of being able to define multiple `generate_hcl` blocks with the same label.

**Comment by sergeyshevch** [comment]
@katcipis Ok thanks for clarifying. I will open it as a feature request in a new feature

**Comment by katcipis** [comment]
Thanks @sergeyshevch :100:
