### ISSUE TITLE
[FEATURE] Switch off the git safeguard checks

### ISSUE THREAD

**Issue by lanejlanej** [mineiros-io/terramate#435]
**Is your feature request related to a problem? Please describe.**
Have terramate project in a git repo, but do not wish to make use of the git integration at this point in time.
So, have simply config {} at top level. However, terramate insists on checking for untracked files etc. It would be good
if that can be switched off.

**Describe the solution you'd like**
config setting to not fuss about git repo if you are not using git integration features

**Describe alternatives you've considered**

**Additional context**

**Comment by katcipis** [comment]
Hi @lanejlanej,

We already plan to add the git checks configurations to the current project wide git config documented [here](https://github.com/mineiros-io/terramate/blob/main/docs/project-config.md#the-terramateconfiggit-block).

That should solve your problem, will let you know as soon as we have it available.

**Comment by lanejlanej** [comment]
Hi Tiago,

That sounds good.

Thanks

**Comment by i4ki** [comment]
Hi @lanejlanej,

We just released Terramate v0.1.13 with the support of disabling the checks through the config and environment variables.

Have a look [here](https://github.com/mineiros-io/terramate/pull/461#issue-1299422513) for usage details.

The docs will be updated soon.
