### ISSUE TITLE
[BUG] Terramate cannot parse overrides the same as terraform does

### ISSUE THREAD

**Issue by frimik** [mineiros-io/terramate#697]
**Describe the bug**

Terramate doesn't parse override files the same as Terraform and errors on for example module override blocks without `source` specifications.

**To Reproduce**

1. Place a module block inside a `vpc.tf` file:
    ```terraform
    module "vpc" {
      source = "terraform-aws-modules/vpc/aws"

      name = "my-vpc"
      cidr = "10.0.0.0/16"

      azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
      private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
      public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
    
      enable_nat_gateway = true
      enable_vpn_gateway = true
    
      tags = {
        Terraform = "true"
        Environment = "dev"
      }
    }
    ```
3. Add a `vpc_override.tf` file, and override the module block. This module block is without a `source =` argument:
    ```terraform
    module "vpc" {
      name = "my-vpc-override"
    }
    ```
4. Run `terramate list --changed` and see example error:
    ```
    2022-11-07T16:30:49+01:00 ERR listing changed stacks error: checking module changes: applying operation to file "foo_override.tf": parsing modules: terraform schema error: module must have a "source" attribute file=/home/dev/dev/tf-stack/foo_override.tf:5,22-8,2
    ```

Adding a "duplicated" source line on all override blocks avoids this issue.

**Expected behavior**
Same parsing functionality as Terraform. Overides to work.

**Environment (please complete the following information):**
 - Terramate Version 0.1.40

**Comment by mariux** [comment]
Hi @frimik 

Thanks for reporting.

Are your overrides in `.gitignore` in your configuration or do you check them in with your normal code?

**Comment by frimik** [comment]
@mariux They are checked in actually.

The added detail is that I've been historically dedup'ing code by symlinking `mixin` base files into the stacks which are "identical", and using `_override.tf` for the few differences there may be between them. For example I may add an override to a certain stack for the `source = ` parameter specifically while promoting a stack to a newer local or upstream module, with very little effort I can isolate one stack from the others while verifying before "going wide" and updating the actual source mixin file(s).

**Comment by katcipis** [comment]
@frimik we selected this bug to be fixed on our current sprint, a fix will be coming soon. Thanks for taking the time to report the issue.
