### ISSUE TITLE
[FEATURE] Print stack on which Terraform commands are ran

### ISSUE THREAD

**Issue by adrienbroyere** [mineiros-io/terramate#815]
**Is your feature request related to a problem? Please describe.**

Maybe I missed something but could not find it by myself. Is there a way to print the stack name or id upon which Terraform commands are ran?

 I am running Terramate on dozens of stacks and the Terraform plan output can be tedious to analyse for a human. Currently, I retrieve the execution order using `terramate experimental run-order` and then I run `terramate run terraform plan`. But from here, I have to mentally link the output of each plan with the execution order.

I notice that all these information are already accessible running the command `terramate experimental metadata` but I do not find a way to retrieve them durring Terramate execution. I am thinking of something alongside (for example) when running `terramate run terraform plan`:

```
-- ${terramate.stack.id} --
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

-- ${terramate.stack.id} --
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

**Describe the solution you'd like**

Here are some idea

- Have a way to access stack’s metadata during a stack execution.
- Print stack metadata before the Terraform command being executed

**Describe alternatives you've considered**

**Additional context**

**Comment by i4ki** [comment]
hey @adrienbroyere 

If you increase log-level to `info` then it prints out the `cmd` and `stack` path, have a look at the output below:

```
$ terramate --log-level=info run -- pwd
2023-01-24T20:13:41Z INF running cmd=pwd stack=/stacks/stack-1
/home/i4k/src/mineiros/stacks/stack-1
2023-01-24T20:13:41Z INF running cmd=pwd stack=/stacks/stack-2
/home/i4k/src/mineiros/stacks/stack-2
...
```
Let me know if this is what you were looking for.

**Comment by adrienbroyere** [comment]
Hi @i4ki 

Thank you for your quick answer. My idea was to create a big tfplan log file for review purposes, I was able to achieve the result with

```
terramate --log-level=info --log-fmt=text run terraform plan -no-color 2>&1 | tee tfplan
```

This way, I have the name of the stack printed before each plan.
I will close this issue, thank you 👍
