### ISSUE TITLE
[BUG] Current directory scope limitation seems to be not working correctly

### ISSUE THREAD

**Issue by brk3** [mineiros-io/terramate#914]
**Describe the bug**
In the (very nice) new [docs](https://terramate.io/docs/cli/orchestration/), it says:

> Terramate uses the current directory it is being executed to filter out stacks, ie., limit the scope of the execution, so if you execute terramate from the project's root directory, all stacks will be selected, and changing to inner directories in the project structure will select only stacks that are children of the current directory.

However, when I have two stacks named as follows:

* `foo/bar/stack-a`
* `foo/bar/stack-b`

If I change into `foo/bar/stack-a` (or use terramates `-chdir`), and do for example `terramate list`, I also see `stack-b` listed.

So, `stack-b` is being selected for execution, which I don't expect given my context is `stack-a`.

Perhaps I'm missing something?

**To Reproduce**

I've set up a repo with the above structure at https://github.com/brk3/terramate-demo

**Expected behavior**
I expected when I'm in a leaf node directory that terramate will only list that for execution.

**Log Output**
```
$ ls
modules          stacks           terramate.tm.hcl
$ terramate list
stacks/test
stacks/test-foo
$ cd stacks/test
$ terramate list
.
-foo
```

Also note that `test-foo` is truncated for some reason.

**Environment (please complete the following information):**
 - OS: MacOS
 - OS Version: Ventura
 - Git Version: git version 2.40.0
 - Terramate Version: 0.2.17

**Comment by mariux** [comment]
@brk3 thanks for raising the issue. This seems to be a weird edge case ;) Your expectations is correct.

@i4ki i can reproduce the issue.

We will check whats going on there and get back to you with details and an ETA for a fix asap..
