### ISSUE TITLE
[SUGGESTION] Add website URL to top of GitHub repo

### ISSUE THREAD

**Issue by mrzmyr** [mineiros-io/terramate#919]
Small suggestions ✨: add the website URL (https://terramate.io/docs) on top of the GitHub repo.

<img src="https://user-images.githubusercontent.com/746429/235880907-9b1e80f0-3752-455d-8359-46ec66a9f4e1.png" width="400" />
<img src="https://user-images.githubusercontent.com/746429/235880913-16d5a848-79ac-4742-a887-2836dc81f814.png" width="400" />

**Comment by soerenmartius** [comment]
That's a great idea - we'll take of it right away! Thanks @mrzmyr !

**Comment by mrzmyr** [comment]
done

**Comment by soerenmartius** [comment]
> done

thanks!
